config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :clinics, :participants, :doctors
  # get '/participants', to:'participants#index'
  # get '/participants/new', to:'participants#new'
  # post '/participants/new', to:'participants#create'
  # get '/participants/:id/show', to:'participants#show'
  # get '/show_me_participants', to: 'participants#show_me_participants'
  resources :clinics do
    resources :arms do 
      resources :participants
    end
  end
  resources :arms do
    resources :participants
  end 
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arm.rb
class Arm < ApplicationRecord
    belongs_to :clinic
    has_many :participants
    validates :limit, numericality: {only_integer: true}
    validates_length_of :participants, maximum: :limit
end

app/models/clinic.rb
# frozen_string_literal: true

class Clinic < ApplicationRecord
    has_many :arms
    validates :name, uniqueness: {case_sensitive: false}
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    validates :name, uniqueness: {case_sensitive: false}
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :arm , optional: true
  validates_associated :arm
  validates :name, :age, :gender, presence: true
  validates :gender, inclusion: { in: %w[Male Female], message: 'Either male or female' }
 #validates :name, uniqueness: {case_sensitive: false}
  validates :age, numericality: { only_integer: true }
  #validates_format_of :name, :with => /\A[a-zA-Z\s]+\Z/
  before_validation :method_before_validation
  after_validation :method_after_validattion

  private

  def method_before_validation
    self.gender = 'Male' if gender.downcase.in? %w[male m]
    self.gender = 'Female' if gender.downcase.in? %w[female f]

    #puts 'Before validation'
  end

  def method_after_validattion
    #puts 'After Validation'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/arms_controller.rb
class ArmsController < ApplicationController
  before_action :find_clinic, only: [:index, :destroy, :new, :create]

    def index
        @arms = @clinic.arms 
      end
    
      def new
        @arm ||= @clinic.arms.new
      end
    
      def show; end
    
      def update; end
    
      def create
        @arm = @clinic.arms.new(permit_params)
        if @arm.save
          redirect_to clinic_arms_path(@clinic.id)
        else
          render :new
        end
      end
     
      def destroy
        @arm=Arm.find(params[:id])
        redirect_to clinic_arms_path(@arm.clinic_id) if @arm.destroy
        
      end
    
      private
    
      def permit_params
        params.require(:arm).permit(:name, :limit, :clinic_id)
      end

      def find_clinic
        @clinic = Clinic.find_by(id: params[:clinic_id])
      end

end

app/controllers/clinics_controller.rb
# frozen_string_literal: true

class ClinicsController < ApplicationController
  def index 
    @clinics = Clinic.all
  end

  def new
    @clinic = Clinic.new
  end

  def show; end

  def update; end

  def create
    clinic = Clinic.new(permit_params)
    if clinic.save
      redirect_to clinics_path
    else
      render :new
    end
  end

  def destroy
    @clinic=Clinic.find(params[:id])
    redirect_to clinics_path if @clinic.destroy
  end

  def show_me_clinics; end

  def permit_params
    params.require(:clinic).permit(:name, :location)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    def index
        @doctors = Doctor.all
      end
    
      def new
        @doctor ||= Doctor.new
      end
    
      def show; end
    
      def update; end
    
      def create
        @doctor = Doctor.new(permit_params)
        if @doctor.save
          redirect_to doctors_path
        else
          render :new
        end
      end
    
      def destroy 
        @doctor=Doctor.find(params[:id])
        if @doctor.destroy
            redirect_to doctors_path 
        end
        
      end
    
      private
    
      def permit_params
        params.require(:doctor).permit(:name, :specification)
      end

end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :find_arm, only: [:index, :destroy, :new, :create]

  def index
    @participants = @arm.participants
  end

  def new
    @participant ||= @arm.participants.new
  end

  def show; end

  def update; end

  def create
    @participant = @arm.participants.new(permit_params)
    if @participant.save
      redirect_to arm_participants_path(@arm.id)
    else
      render :new
    end
  end

  def destroy
    @participant = Participant.find(params[:id])
    if @participant.destroy
      redirect_to arm_participants_path(@participant.arm_id)
    end
  end

  private

  def permit_params
    params.require(:participant).permit(:name, :age, :gender, :arm_id)
  end

  def find_arm
    @arm = Arm.find_by(id: params[:arm_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/arms_helper.rb
module ArmsHelper
end

app/helpers/clinics_helper.rb
# frozen_string_literal: true

module ClinicsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/participants_helper.rb
# frozen_string_literal: true

module ParticipantsHelper
end

app/views/arms/index.html.erb
<h1> Show All the arms </h1>
<%= link_to "Clinics List", clinics_path %>
<%= link_to "Create new arm", new_clinic_arm_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Limit</th>
    <th>Clinic Name</th>
  </tr>
  <% @arms.each do |arm| %>
    <tr>
      <td><%= arm.id %></td>
      <td><%= arm.name %></td>
      <td><%= arm.limit %></td>
      <td><%= arm.clinic.name if arm.clinic %></td>
      <td><%= link_to "Delete",arm, method: :delete %></td>
      <td><%= link_to "Participants", arm_participants_path(arm.id) %></td>
      </ br>
    </tr>
  <% end %>
</table>

app/views/arms/new.html.erb
<h1> New arm</h1>
<% if @arm.errors.present? %>
<ul>
<%@arm.errors.full_messages.each do |error|%>
<li><%= error %></li>
    <% end %>
</ul>
<% end %>
<%= form_with(model: @arm, url: clinic_arms_path(@clinic.id)) do |f| %>
<p> 
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label "Limit" %>
    <%= f.text_field :limit %>
    </p>
    <%= f.submit 'Create' %>
<%end%>

app/views/clinics/index.html.erb
<h1> Show all CLINICS </h1>
<%= link_to " add new clinic", new_clinic_path %>
<table>
<tr>
<th>ID</th>
<th>Name</th>
<th>Location</th>
</tr>
<tr>
<% @clinics.each do |clinic| %>
    <td><%= clinic.id %></td>
    <td><%= clinic.name %></td>
    <td><%= clinic.location %></td>
    <td><%= link_to "Delete",clinic, method: :delete %></td>
    <td><%= link_to "Arms", clinic_arms_path(clinic.id) %></td>
    </ br>
</tr>
<% end %>

</table>

app/views/clinics/new.html.erb
<h1>New CLINIC</h1>
<% if @clinic.errors.present? %>
<ul>
<%@clinic.errors.full_messages.each do |error|%>
<li><%= error %></li>
    <% end %>
</ul>
<% end %>
<%= form_with(model: @clinic, local: true) do |f| %>
    <p>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label "Location" %>
    <%= f.text_field :location %>
    </p>
    <%= f.submit 'Create' %>
<%end%>

app/views/doctors/index.html.erb
<h1> Show All the arms </h1>

<%= link_to "Create new doctor", new_doctor_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Specification</th>
  </tr>
  <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.id %></td>
      <td><%= doctor.name %></td>
      <td><%= doctor.specification %></td>
      
      <td><%= link_to "Delete",doctor, method: :delete %></td>
      
      </ br>
    </tr>
  <% end %>
</table>

app/views/doctors/new.html.erb
<h1> New arm</h1>
<% if @doctor.errors.present? %>
<ul>
<%@doctor.errors.full_messages.each do |error|%>
<li><%= error %></li>
    <% end %>
</ul>
<% end %>
<%= form_with(model: @doctor, local: true) do |f| %>
<p>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label "Specification" %>
    <%= f.text_field :specification %>
    </p>
    <%= f.submit 'Create' %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MimicMedidataPgsql</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/index.html.erb
<h1> Show all Participants </h1>
<%= link_to "Arms_List",clinic_arms_path(@arm.clinic.id)%>
<%= link_to "Create new participant", new_arm_participant_path(@arm.id) %>
<table>
<tr>
<th>ID</th>
<th>Name</th>
<th>Age</th>
<th>Gender</th>
<th>Arm Name</th>
</tr>

<% @participants.each do |participant| %>
<tr>
    <td><%= participant.id %></td>
    <td><%= participant.name %></td>
    <td><%= participant.age %></td>
    <td><%= participant.gender %></td>
    <td><%= participant.arm.name if participant.arm %></td>
    <td><%= link_to "Edit Participant", edit_arm_participant_path(@arm.id, participant.id) %></td>
    <td><%= link_to "Delete Participant", participant, method: :delete%></td>
    
    </ br>
</tr>
<% end %>

</table>

app/views/participants/new.html.erb
<h1>New Participant</h1>
<% if @participant.errors.present? %>
<ul>
<%@participant.errors.full_messages.each do |error|%>
<li><%= error %></li>
    <% end %>
</ul>
<% end %>
<%= form_for(@participant, url: arm_participants_path(@arm.id)) do |f| %>
  <p>
  <%= f.label 'Name' %>
  <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'Age' %>
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label 'Gender' %>
    <%= f.text_field :gender %>
  </p>
  <%= f.submit 'Create' %>
<% end %>

app/views/participants/show.html.erb
<h3>Show Participant</h3>

app/views/participants/show_me_participants.html.erb
<p>Displaying all participants</p>